import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import ChoiceCopnent from "@/Components/ChoiceCopnent";
import Properties from "@/Components/Properties";
import Slider from "@/Components/Slider";

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(` https://63bd70b818bc301c0267c02b.mockapi.io/api/v1/properties?page=1&limit=10`)
  const data = await res.json()
  const image = await fetch(`https://63bd70b818bc301c0267c02b.mockapi.io/api/v1/home_images`)
  const images = await image.json()
 // Pass data to the page via props
  return { props: { data ,images} }
}
export default function Home({data,images}) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <Slider images={images}/>
   <ChoiceCopnent/>
  <Properties data={data}/>
  </main>
    </>
  )
}
